### PR TITLE
add resync controller 

### PR DESCRIPTION
**Pull request by haoqing0110**
The related feature request: open-cluster-management-io/community#52
Ref: https://github.com/open-cluster-management/backlog/issues/18210

Signed-off-by: haoqing0110 <qhao@redhat.com>

In the benchemark testing, then resync interval is 5 seconds, the schedule time of 100000 placements reduce about 20s. 

Before (resync in the same controller with [code](https://github.com/haoqing0110/placement/commit/546eefb94d7621a700677f98a815f66fc33771be))
```
# go test -bench="BenchmarkSchedulePlacements100000$"
goos: linux
goarch: amd64
pkg: open-cluster-management.io/placement/test/benchmark
cpu: Intel Core Processor (Haswell, no TSX)
BenchmarkSchedulePlacements100000-24                   1        279440555550 ns/op
PASS
ok      open-cluster-management.io/placement/test/benchmark     279.802s
-
```

After  (resync in the new controller)
```
#  go test -bench="BenchmarkSchedulePlacements100000$"
goos: linux
goarch: amd64
pkg: open-cluster-management.io/placement/test/benchmark
cpu: Intel Core Processor (Haswell, no TSX)
BenchmarkSchedulePlacements100000-24                   1        255090872924 ns/op
PASS
ok      open-cluster-management.io/placement/test/benchmark     255.366s
```

### CODE REVIEW

**Comment by haoqing0110** [comment]
@qiujian16 any suggestion on the benchmark testing? don't see a big improvement when adding another controller.

**Comment by qiujian16** [comment]
what is the reconcile time for each placement? How many clusters in your test. I think we will have to consider parallel

**Comment by haoqing0110** [comment]
Update the benchmark testing, create 1000/10000 placement in env with 1000 clusters and 1000 addon scores. Below are the total time to schedule all the placements:

Resync in the same controller (with code [here](https://github.com/haoqing0110/placement/commit/1a54b1ab8ba5569f645198aee1fbbec9fb3f80f5))
```
# go test -bench="BenchmarkSchedulePlacements1000$"
goos: linux
goarch: amd64
pkg: open-cluster-management.io/placement/test/benchmark
cpu: Intel Core Processor (Haswell, no TSX)
BenchmarkSchedulePlacements1000-24             1        14613978548 ns/op
PASS
I0118 08:28:45.375109 3827872 base_controller.go:166] Shutting down SchedulingController ...
ok      open-cluster-management.io/placement/test/benchmark     30.056s
```
```
# go test -bench="BenchmarkSchedulePlacements10000$"
goos: linux
goarch: amd64
pkg: open-cluster-management.io/placement/test/benchmark
cpu: Intel Core Processor (Haswell, no TSX)
BenchmarkSchedulePlacements10000-24            1        306247209814 ns/op
PASS
I0118 08:41:38.465052 3830250 base_controller.go:166] Shutting down SchedulingController ...
ok      open-cluster-management.io/placement/test/benchmark     321.011s
```
Resync in the new controller (with this PR)
```
# go test -bench="BenchmarkSchedulePlacements1000$"
goos: linux
goarch: amd64
pkg: open-cluster-management.io/placement/test/benchmark
cpu: Intel Core Processor (Haswell, no TSX)
BenchmarkSchedulePlacements1000-24             1        12399352374 ns/op
PASS
I0118 08:19:39.180974 3824050 base_controller.go:166] Shutting down SchedulingControllerResync ...
ok      open-cluster-management.io/placement/test/benchmark     26.600s
```
```
# go test -bench="BenchmarkSchedulePlacements10000$"
goos: linux
goarch: amd64
I0118 08:25:41.722598 3824874 base_controller.go:166] Shutting down SchedulingController ...
pkg: open-cluster-management.io/placement/test/benchmark
cpu: Intel Core Processor (Haswell, no TSX)
BenchmarkSchedulePlacements10000-24            1        273870701609 ns/op
PASS
I0118 08:25:41.722711 3824874 base_controller.go:166] Shutting down SchedulingControllerResync ...
ok      open-cluster-management.io/placement/test/benchmark     289.023s
```

**Pull request merged**
